sudo: false
language: go
branches:
  only:
    - master

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

env:
  global:
    - GOARCH=amd64
    - TRAVISTEST=true

before_install:
  - go get "github.com/chewxy/tightywhities"
  - go get "gorgonia.org/tensor"
  - go get "github.com/pkg/errors"
  - go get "gorgonia.org/dawson"
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci


matrix:
  allow_failures:
    - go: tip